/*******************************************************************************
 * Copyright (C) 2021 the Eclipse BaSyx Authors
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 ******************************************************************************/
package org.eclipse.basyx.wrapper.receiver;

/**
 * A listener for values that have been generated by the wrapper
 * 
 * @author espen
 *
 */
public interface IWrapperListener {
	/**
	 * Informs the listener about a new value that has been generated
	 * 
	 * @param result
	 */
	public void newValue(String propId, PropertyResult result);
}
