version: '3.8'
services:
  registry:
    image: eclipsebasyx/aas-registry:1.0.2
    environment:
        - basyxregistry_registry_backend=InMemory
        - basyxcontext_contextpath=/registry
        - basyxcontext_contextport=4000
    container_name: registry
    ports:
      - 4000:4000

  aas:
    image: eclipsebasyx/aas-server:1.1.0-SNAPSHOT
    container_name: aas
    ports:
      - 4001:4001
    environment:
        - basyxaas_registry_path=http://registry:4000/registry/
        - basyxaas_aas_backend=InMemory
        - basyxcontext_contextpath=/aasServer
        - basyxcontext_contextport=4001
        - basyxaas_aas_source=aasx/01_Festo.aasx
        - waiting_for=[{"host":"registry","port":"4000"}]
